### ISSUE TITLE
Is it possible to put weights on clusters?

### ISSUE THREAD

**Issue by xinkai-zhou** [JuliaStats/MixedModels.jl#221]
The package currently supports "case weights" - weights on individual observations. I wonder if there is an easy way for me tweak the code so that I can put weights on clusters? Thank you.

**Comment by Nosferican** [comment]
Could you expand on what you mean by weights on clusters?

**Comment by xinkai-zhou** [comment]
Sure. If I understand correctly, in the MLE approach, the package calculates the log-likelihood ```l_i``` for cluster ```i``` and sum over all clusters to obtain the total log-likelihood ```l = \sum l_i```. I wonder if there is a way to tweak the code so that I can calculate ``` \sum w_i l_i``` where ```w_i``` is the weight for cluster ```i```.

**Comment by palday** [comment]
This could potentially be done in the objective, but it's also somewhat missing the usual point of mixed effects models. In some sense, the clusters are being weighted based on the amount of data and the signal-to-noise ratio in that data for each cluster. Or more directly: the amount of shrinkage applied to a given cluster can be thought of as a type of weighting of that cluster. This is exactly what weighting the clusters would do, but it's the basic idea. 

Rather than having cluster-weights as a separate thing, my preference would be to have the cluster weights integrated into the case weights by some wrapper machinery and leave the internal fitting as is. This would then wind up working similar to the re-weighting that goes on in GLMM. We have long-term plans to refactor some of the code there to make it easier/more obvious for other similar applications: more general pre-whitening, AR terms, additional variance-structures, etc. 

In the meantime, my suggestion would be just pre-compute the combined case+cluster weight and use that as a case weight.

**Comment by xinkai-zhou** [comment]
@palday 

Thanks for getting back. 

If I understood correctly, for linear mixed models, I can just modify [this line](https://github.com/JuliaStats/MixedModels.jl/blob/a2617adae0c31609789c164a3e87522469a79bb8/src/linearmixedmodel.jl#L529).

However, for generalized mixed models, I'm looking at this [deviance function](https://github.com/JuliaStats/MixedModels.jl/blob/a2617adae0c31609789c164a3e87522469a79bb8/src/generalizedlinearmixedmodel.jl#L62) and don't know which variable corresponds to weights. 

> In the meantime, my suggestion would be just pre-compute the combined case+cluster weight and use that as a case weight.

Correct me if I'm wrong, but I don't think the particular cluster weight that I have in mind can be massaged into case weights at the moment, because ```\sum log(w_ij * P(y_ij)) = \sum log(w_ij) + \sum log(P(y_ij))```, so the case weights appear as additive terms in the log-likelihood, but I need them to be multiplicative (```\sum w_i l_i```).

**Comment by palday** [comment]
Without commenting on or even thinking about the statistical end of your proposal .... if you want something to be multiplicative on the log scale, you make it exponential on the original scale. 

For GLMM, the weights are more complicated because they're tied into the particular response family. See [`deviance!`](https://github.com/JuliaStats/MixedModels.jl/blob/a2617adae0c31609789c164a3e87522469a79bb8/src/linearmixedmodel.jl#L529-L533) for a better starting point.

But again, why do you want to do this?
