### ISSUE TITLE
Nested model MethodError, Array{Float62, 2} vs SparseMatrixCSC{Float64,Int32}?

### ISSUE THREAD

**Issue by vals** [JuliaStats/MixedModels.jl#232]
Hi,

I was fitting a model of the style `y ~ 1 + (1 | A) + (1 | Ab)`, where unique `Ab` levels are nested within `A`. There are 5 levels of `A` and 1,599 levels of `Ab`, with 4,755 observations.

Then I wanted to try a rougher, alternative, stratification of `A`. So that `A` would have 3 levels (instead of 5). Using the same formula, the `fit` function throws a `MethodError`:

```
MethodError: no method matching rankUpdate!(::LinearAlgebra.Diagonal{Float64,Array{Float64,1}}, ::Array{Float64,2}, ::Float64)
[...]
rankUpdate!(::LinearAlgebra.Diagonal{T<:Number,V} where V<:AbstractArray{T<:Number,1}, !Matched::SparseMatrixCSC{T<:Number,Ti} where Ti<:Integer, ::Any) where T<:Number at /home/ubuntu/.julia/packages/MixedModels/qyKOf/src/linalg/rankUpdate.jl:52
[...]
```
I looked at the `describeblocks` output for the two models:
`A` with 5 levels (which works):
```
lmm = LinearMixedModel(fm1, df)
describeblocks(lmm)
1,1: LinearAlgebra.Diagonal{Float64,Array{Float64,1}} (1599, 1599) LinearAlgebra.Diagonal{Float64,Array{Float64,1}}
2,1: SparseMatrixCSC{Float64,Int32} (5, 1599) SparseMatrixCSC{Float64,Int32}
2,2: LinearAlgebra.Diagonal{Float64,Array{Float64,1}} (5, 5) LinearAlgebra.Diagonal{Float64,Array{Float64,1}}
3,1: Array{Float64,2} (1, 1599) Array{Float64,2}
3,2: Array{Float64,2} (1, 5) Array{Float64,2}
3,3: Array{Float64,2} (1, 1) Array{Float64,2}
4,1: Array{Float64,2} (1, 1599) Array{Float64,2}
4,2: Array{Float64,2} (1, 5) Array{Float64,2}
4,3: Array{Float64,2} (1, 1) Array{Float64,2}
4,4: Array{Float64,2} (1, 1) Array{Float64,2
```
`A` with 3 levels (which doesn't work):
```
lmm = LinearMixedModel(fm1, df2)
describeblocks(lmm)
1,1: LinearAlgebra.Diagonal{Float64,Array{Float64,1}} (1599, 1599) LinearAlgebra.Diagonal{Float64,Array{Float64,1}}
2,1: Array{Float64,2} (3, 1599) Array{Float64,2}
2,2: LinearAlgebra.Diagonal{Float64,Array{Float64,1}} (3, 3) LinearAlgebra.Diagonal{Float64,Array{Float64,1}}
3,1: Array{Float64,2} (1, 1599) Array{Float64,2}
3,2: Array{Float64,2} (1, 3) Array{Float64,2}
3,3: Array{Float64,2} (1, 1) Array{Float64,2}
4,1: Array{Float64,2} (1, 1599) Array{Float64,2}
4,2: Array{Float64,2} (1, 3) Array{Float64,2}
4,3: Array{Float64,2} (1, 1) Array{Float64,2}
4,4: Array{Float64,2} (1, 1) Array{Float64,2}
```
It does appear that in the version with more levels there is a sparse matrix, while not in the one with fewer levels.

Is there a way I should be creating the model or formula to ensure it makes a sparse matrix?

Best,
/Valentine

**Comment by palday** [comment]
Without having actually taken the time to look at your block descriptions closely (though thank you for looking around enough to know to do that! -- that's ultimately very useful information for us), I have two comments / suggestions.

1. With 5 levels, you're already getting quite close to the point where it really doesn't make sense to model it as a grouping factor in the RE and should think about having it as a fixed effect (with interactions). With 3 levels, I would just treat it as a FE. See e.g. the [GLMM FAQ](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#should-i-treat-factor-xxx-as-fixed-or-random). This is probably what's going wrong: with so few levels, the second set of blocks becomes effectively dense and not sparse.

2. The multiplication methods are currently undergoing a major change to take advantage of some new functionality in Julia 1.3 and greatly reduce our maintenance overhead, so we won't add in additional specialized methods for the old framework. What happens if you try your example on Julia 1.3 with the new methods? You can install the relevant development version via 

```julia
julia> using Pkg; Pkg.add("MixedModels.jl#dropmulalphabeta")
```

**Comment by vals** [comment]
Hi Phillip, 

Thanks for getting back to me. I upgraded my Julia to 1.3, and installed the `dropmulalphabeta` branch. (Though, I had to change the command to `Pkg.add(PackageSpec(url="https://github.com/JuliaStats/MixedModels.jl", rev="dropmulalphabeta"))` for some reason).

The problem is still there with the new version.

I will try using a fixed effect instead. So I'm clear, the model you would propose is in my case `y ~ 1 + A + (1 | Ab)`? Or is there something special I should do for the interaction you mention?

Regards,
/Valentine

**Comment by palday** [comment]
Ah, you have an intercepts-only model, so there's no interactions to speak of.  You should still slightly change your model to use effects coding so that the intercept keeps its current interpretation as a the grand mean (and not the mean of the reference level):

`LinearMixedModel(@formula(y ~ 1 + A + (1 | Ab)), data, constrasts=Dict(:A => EffectsCoding()))`

**Comment by vals** [comment]
Hi,

I just wanted to get back to you that I followed your suggestion (and also read up on the difference contrast codings in the StatsModels documentation).

Thanks! Closing the issue.
