### ISSUE TITLE
Variable ordering is wrong

### ISSUE THREAD

**Issue by liamlundy** [JuliaStats/MixedModels.jl#242]
Basically I am getting mismatched coefficients and variables when a column is all 0's. I've included an example below showing the input data and the model result. Variable `a` is all 0's, but all the other variables should have valid coefficients and `b` does not.

I'm guessing that somehow the data for `a` gets removed because it's constant, but gets improperly added to the result. It seems like this case should either be fully supported or explicitly fail.

This example was created using MixedModels v2.2.0
```
using DataFrames, Random, MixedModels, StatsModels

rng = MersenneTwister(53);
data = DataFrames.DataFrame(
    a=repeat([0.0], 20),
    b=rand(rng, 20),
    c=rand(rng, 20),
    y=rand(rng, 20),
    category=repeat([1,2,3,4], 5)
)

categorical!(data, [:category])

f = Meta.parse("y ~ a + b + c + (1 + c | category)")
model_form = @eval StatsModels.@formula($f)
model = LinearMixedModel(model_form, data)
fit!(model)
```
Output:
```
Linear mixed model fit by maximum likelihood
 y ~ 1 + a + b + c + (1 + c | category)
   logLik    -2 logLik      AIC         BIC
 -0.63159143  1.26318286 17.26318286 25.22904105

Variance components:
            Column               Variance                  Std.Dev.         Corr.
category (Intercept)  0.00000000000000000000000000000 0.000000000000000000
         c            0.00000000000000000000022822322 0.000000000015107059   NaN
Residual              0.06236706649847829908583918268 0.249733991475886791
 Number of obs: 20; levels of grouping factors: 4

  Fixed-effects parameters:
────────────────────────────────────────────────────────
               Estimate   Std.Error     z value  P(>|z|)
────────────────────────────────────────────────────────
(Intercept)   0.286783     0.143214    2.00248    0.0452
b            -0.0        NaN         NaN          NaN
c             0.0450868    0.233915    0.192749   0.8472
a             0.212049     0.209424    1.01253    0.3113
────────────────────────────────────────────────────────
```

**Comment by palday** [comment]
One of the first things I learned in computer science was *garbage in, garbage out*. 

That said, I think the row labelling is what's going wrong here: for a constant-zero predictor the coefficient is not uniquely defined, so in that sense, zero would be a valid estimate with undefined standard errors and hence z- and p-values. Since this is in the fixed effects, it's taking advantage of [`StatsModels`](github.com/JuliaStats/StatsModels.jl/) machinery. 

Maybe @kleinschmidt has an idea about what's going wrong? 

What happens when you do a non-mixed GLM? Can you modify your example so that's reproducible? Examples with random-number generation aren't strictly reproducible without setting the random number generator and seed, see [here](https://gist.github.com/palday/0ce66d7a2c404a129430fa4a848d6518) for an example.

**Comment by liamlundy** [comment]
Thank you for taking a look at this @palday . I edited the original example to set a seed. The effect should be consistently reproducible either way, but the numbers are as well now.

This example will fail with the following error in GLM: `ERROR: PosDefException: matrix is not positive definite; Cholesky factorization failed.`

Just to be clear, I'm not contending that there should be valid result here. Instead this data case needs to be fully supported, or fail explicitly like GLM. I am happy to create a fix for this if someone can point me at the underlying problem and dictate the desired behavior.

**Comment by kleinschmidt** [comment]
Does MixedModels not do the same posdef check that GLM does? Is there a reason for that?

**Comment by palday** [comment]
I suspect it's because fixed effects are boring. ;) But also because that fixed effects are marginalized out before the non linear optimization of the random effects takes place, where most of the work has been done. Skimming the code quickly, there are some checks based on rank and permuting the model matrix (the latter is probably why the ordering is wrong), but nothing checking positive definiteness. I don't think it's the case in general, but it might be that the random effects weaken some of the constraints on the fixed-effects model matrix. There is one special case where this is definitely true: strictly speaking, you can have a model without any fixed effects at all, although that may not yet work computationally:


I'm loathe to add a special check for "is this column constant zero?"  or even "is this column just an arbitrary constant?", especially because the latter might make occasionally sense for some unusual formula specifications.

**Comment by dmbates** [comment]
I think @palday is correct that the numbers are correct but the labels are wrong.  An `FeMat` has a pivot vector and a computational rank stored with it. The `coef` extractor is supposed to undo the pivoting but apparently it doesn't get the order of the column names `cnames` correct when it undoes the pivot.

Do you want me to look at this, @palday, or is this enough info for you to look at it?  I am doing something similar right now with respect to profiling the deviance so it is not a big deal for me to check on this too.

**Comment by dmbates** [comment]
It probably wouldn't be the worst thing in the world to handle the case of zero columns separately in the `FeMat` constructor. It actually works properly now except that it doesn't get the rank correct.
```julia
julia> MixedModels.FeMat(ones(10,0), String[])
MixedModels.FeMat{Float64,Array{Float64,2}}(Array{Float64}(undef,10,0), Array{Float64}(undef,10,0), Int64[], 140633143403952, String[])
```
I don't think we need to address this right now in that this is not the case in the example here.  But eventually for profiling I will need to be a bit more careful.

**Comment by dmbates** [comment]
By the way, "that fixed effects are marginalized out before the non linear optimization of the random effects takes place" is not accurate.  A better way to say what is happening is that the evaluation of the objective profiles out the fixed effects parameters.  This will become clear in the paper that we are writing - hint, hint.

**Comment by palday** [comment]
@dmbates If everybody can wait a few days, I'll take a look at it and it'll be a nice way for me to get more familiar with the fixed-effects portion of the codebase. I'm somewhat satisfied with myself for feeling somewhat uneasy about my summary of the handling of the fixed effects, even if I want ahead and used it anyway. :man_facepalming:

**Comment by palday** [comment]
The actual estimation handles this correctly, but it seems the pivot isn't tracked in all the accessor/`show` methods:

```julia
julia> fixef(model)
3-element Array{Float64,1}:
 0.286782665154682  
 0.04508676247317425
 0.21204863902299712

julia> coef(model)
4-element Array{Float64,1}:
  0.286782665154682  
 -0.0                
  0.04508676247317425
  0.21204863902299712

julia> coeftable(model)
────────────────────────────────────────────────────────
               Estimate   Std.Error     z value  P(>|z|)
────────────────────────────────────────────────────────
(Intercept)   0.286783     0.143214    2.00248    0.0452
b            -0.0        NaN         NaN          NaN   
c             0.0450868    0.233915    0.192749   0.8472
a             0.212049     0.209424    1.01253    0.3113
────────────────────────────────────────────────────────
```
