### ISSUE TITLE
thread parametricbootstrap

### ISSUE THREAD

**Issue by yakir12** [JuliaStats/MixedModels.jl#311]
To save time, if at all possible, it would be cool to allow for threading in `parametricbootstrap`.

**Comment by palday** [comment]
This is already available in the development version (but won't be available in a release until 3.0, because it ties deeply into the new bootstrap structure, which is a breaking change and thus requires a major release).

**Comment by yakir12** [comment]
Cool! I'll try it now (on #master?)

**Comment by palday** [comment]
Exactly.

**Comment by yakir12** [comment]
hmm... cpu is as low as before (albeit I have a feeling it's faster). Was there some special syntax? My Julia session is on 32 threads...

**Comment by yakir12** [comment]
nm, found it. use_threads

**Comment by yakir12** [comment]
ok, just some feedback, though let me know if you'd rather have it somewhere else than this "issue". On master, without threading it took 4:37, and with threading it took 2:42. Since I have 32 threads enabled in this session, I greedily expected it to take about 4:37/32 = 9 seconds + overhead. I did notice that the progress bar halted multiple times. So it went quick and then paused. Maybe I should adjust the number of threads I start my Julia sessions with. The number 32 comes from some calculation I found online (can't find it now, though it made sense at the time)... Hope this is helpful

**Comment by palday** [comment]
How many physical cores and how much RAM do you have? How many bootstrap samples? How long did fitting the original model take?

**Comment by yakir12** [comment]
> How many physical cores?
```
~$ lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Socket(s):                       1
NUMA node(s):                    1
Model name:                      AMD Ryzen Threadripper 2950X 16-Core Processor
NUMA node0 CPU(s):               0-31
```
> how much RAM do you have? 

125 GB
> How many bootstrap samples? 

100_000
> How long did fitting the original model take?

on master? As I said it took 00:04:37. I don't remember how much it took on the stable branch (but I could check if it helps somehow).

**Comment by palday** [comment]
For fitting -- not the bootstrap samples, but the original `fit(MixedModel...`) call. (I have my suspicions about why you're not seeing linear speed up, but I want be as specific as possible in my speculations. :) )

**Comment by yakir12** [comment]
```julia
julia> @time tx = fit(MixedModel, @formula(v ~ y + 1 + (1 + y|id)), data)#, Gamma(), LogLink())
  0.470633 seconds (998.61 k allocations: 52.184 MiB)
```
I'd really want to use a Gamma family (dependent variable `v` is velocity, in my case speed can only be positive), but I got some errors on it on stable (NLopt stepsize, I think), I'll try now to see if master can solve it.

**Comment by yakir12** [comment]
And gamma worked!
```julia
julia> @time tx = fit(MixedModel, @formula(v ~ y + 1 + (1 + y|id)), data, Gamma(), LogLink())
 10.307857 seconds (13.83 M allocations: 904.844 MiB, 1.69% gc time)
```
and that's the time it took. Let me know if you need me to use `@btime` instead.

**Comment by yakir12** [comment]
Oh, I can't bootstrap the parameters with a **Generalized** Linear Mixed Model... Oh! I can  `predict` GLMM!!! Cool!

**Comment by palday** [comment]
`@time` will give a nice upper bound. :)

Sidebar: If you have nice Gamma dataset that you can contribute in some way, we'd be very interested. I've been doing a lot of work on the less "loved" GLMM families (i.e. not Binomial/Bernoulli and not Poisson) and I've been somewhat hindered by not having a good real-world dataset. 

I have another meeting going on, but I'll speculate in detail in a little bit about what's happening -- don't feel offended if I explain the obvious, I'm taking the opportunity to document some behavior that may need be obvious if you don't know the internals.

**Comment by yakir12** [comment]
I know very little and am almost never offended by anything!

It's hardly nice in its gamma-ness:
![a](https://user-images.githubusercontent.com/3281957/81174258-cffa1080-8fa1-11ea-8239-ee18ec6c9605.png)
but let me know how I can contribute it and I will.

I now realized that I can't use predict to get some confidense intervals on the data, which is why I was using the bootstrap method instead. But now that both are not possible with a GLMM then I'll probably revert to a linear mixed model. 

Thanks a lot for all the rapid help. And whenever you like, let me know if and how I can help you further.

**Comment by palday** [comment]
So let's start with the hardware. You have 16 physical cores in your processor, but 32 logical processors or "threads". (Physical) Cores are proper full processors in their own right, but they are printed on the same silicon die and may share memory pathways/buses/caches. Different manufacturers uses different techniques for hardware threads, but the basic idea is that modern CPUs/CPU cores are large complex entities with many subunits  and that a given (software) thread may not be using all the units at one time. So instead of letting those units lie idle, you can treat those units as an additional virtual core that can handle some work. So far, so good. The problem is that the devil is in the details about which capabilities are free at any time and how well the CPU can schedule the virtual CPUs onto the capabilities of the physical CPUs. So hardware threads definitely open up some unused potential, but they're not the same as having additional physical cores.

On the next level is the layer of software threading. Your computer is always doing various things in the background, even if you're not doing something like watching YouTube on the side or listening to music, all of which correspond to one or more (software) threads and consume some CPU resources. Then within numeric software such as MixedModels, there are also multiple layers. For a lot of the linear algebra, we take advantage of BLAS software. Many linear algebra operations can be parallelized in various different forms (which is GPUs are so great for them -- they are designed to have exactly the type of parallelism that you need for linear algebra), so a lot of BLAS software has varying amount of support for multi-threading. So even if we're not doing high-level stuff in parallel, you may get some parallelization depending on the BLAS software you're using (and this is a source of discussion and development in some corners of the Julia community).

Finally, we have the top level where we're doing the multithreading in MixedModels. Because we do most of our matrix operations in place, we first have to copy the model in the question so that each thread gets a copy. We only have to do this once, but for large models or large numbers of threads, this copy step can take a while (and can create problems if you're on a limited memory system). Each thread has its own local storage, but they all share a single random number generator (RNG). Sharing an RNG has a several advantages, but perhaps most importantly you get the same results for a given seed no matter how many threads you have (which is different from many other types of parallel simulation, where the initial seed is used to seed new RNGs for each thread and so your random number stream is dependent both on the original seed and the total number of threads). We have a test for this in our testsuite that compares the single-threaded result with a multi-threaded result where we artificially delay one of the threads to reflect the non determinism of thread scheduling in real-world use. 

The downside to this approach is that the RNG serves as a bottleneck -- every thread has to get exclusive access to the RNG for the `simulate!` step that forms the core of the parametric bootstrap. For large but easy to fit models, this means that this creates a big blockage because we have to generate a lot of random numbers, but don't spend much time fitting. However, we usually assume that the majority of the time is spent in refitting the (copied) model to the simulated data. So while thread i is fitting, thread i+1 is getting its random numbers, and hopefully thread i+2 is just finishing fitting, etc. 

Finally, all of this interacts with the threading happening at lower levels. So if your BLAS is multithreaded, then not all of the processor threads (whether hardware or software) are available for fitting multiple models in parallel. Moreover, hardware threads don't always work great for large, complex numerical problems because such problems tend to take advantage of processor resources that aren't overprovisioned and thus shared between hardware threads (assuming a sufficiently good compiler that takes advantage of things like SIMD, which is generally true of the compiler technology underlying Julia for well written loops). So now instead of each software bootstrap thread getting its own hardware thread to run on, it's fighting with a bunch of other threads. Swapping threads (or more technically, a context switch) has its own costs, so in addition to there being less time per thread, we also have time wasted on switching. 

So what does this mean in practice? For a small number of threads, you'll get nearly linear speed up for each additional thread, minus the overhead. But for larger ones, you'll eventually hit a point where don't get that speed up. The `use_threads` parameter is intentionally very simple in MixedModels and we don't allow the user to specify the number of threads (which I'm thinking we should now do....), so we always use the Julia-level `NUM_THREADS`. For your processor configuration, I would recommend 16. If everything is horrible in terms of contention between threads, then that's still no more than your total number of real cores, and the underlying BLAS library might still be able to take advantage of the additional hardware threads. I have given some thought to being smarter about the RNG, but that would introduce so much more bookkeeping and code complexity that this might make it slower for a small number of threads. (In other words: I might revisit this in the future, but it's not high priority.) 

Also, I'm very jealous of your computer. :)

**Comment by palday** [comment]
About your data: we need both nice data (which we could also simulate) and slightly messy real-world data. The best way to contribute is to post the CSV or Feather file somewhere public (or send me a link via email) and we'll add it in as an artefact. Also, let us know how you want to be cited/referenced. :)

The only thing holding back bootstrapping for GLMM is a missing `simulate!` for GLMM, which is not too terribly hard, but quite tedious in terms of bookkeeping. I have this flagged for 3.0. 

`predict` for both LMM and GLMM is a bit harder. For both, there's the question about how to handle the random effects (leave them out? simulate new levels of the grouping variables? only work for observed levels of the grouping variables? what about a mixture of these things, i.e. omit some but not all RE?). For GLMM, you also have to handle all the bookkeeping you need for `simulate`, such as in adding noise from the appropriate family/distribution and then how to handle the link function (i.e. either return results on the scale of the linear predictor or on the scale of the response). Not terribly hard to do for the simple case, but quite a lot of tedious detail and designing a flexible but easy to use interface for all these options is non trivial. Even after years of using `lme4`, I still have to read the docs for its `predict` function every time I use it.

**Comment by yakir12** [comment]
(I want to benchmark my case with various number of threads, hopefully next week)
