### ISSUE TITLE
`invalid git HEAD` when trying to add the master branch

### ISSUE THREAD

**Issue by likanzhan** [JuliaStats/MixedModels.jl#321]
I had the following error?

```
(@v1.4) pkg> add MixedModels#master

ERROR: invalid git HEAD (reference 'refs/heads/master' not found)
```
What could be the reason ?

Thanks.

**Comment by palday** [comment]
I have no idea, but I don't think it's a problem in MixedModels -- our master branch is definitely present. I suspect something is wrong either with your Internet connection or your local configuration, because you should get a message about updating or cloning the repository:

```julia
(@v1.4) pkg> add MixedModels#master
   Updating git-repo `https://github.com/JuliaStats/MixedModels.jl.git`
  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
  [ff71e718] + MixedModels v2.2.0 #master (https://github.com/JuliaStats/MixedModels.jl.git)
   Updating `~/.julia/environments/v1.4/Manifest.toml`
 [no changes]
```

You might be better off asking this question on the Julia [Slack](https://julialang.slack.com/) / [Zulip](https://julialang.zulipchat.com) / [Discourse](https://discourse.julialang.org/).

It would also be helpful if you provided the output of `versioninfo`:
```julia
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, ivybridge)
Environment:
  JULIA_NUM_THREADS = 2
```

**Comment by likanzhan** [comment]
@palday 

I finally succeed after 
deleting the `.julia` folder to reinitialize  the General registry and 
several attempts to run 
`(@v1.4) pkg> add MixedModels#master`

Thanks.

**Comment by cossio** [comment]
I'm having this issue right now, with a different repo. Is there an upstream issue about this?

**Comment by cossio** [comment]
(Regarding the original issue here, note that the default branch of this repo is `main`, not `master`, as noted by Ian Butterworth)

**Comment by palday** [comment]
@cossio At the time of the original issue, the default branch was indeed `master`. 

There is no upstream issue that I'm aware of, it appears to be a 'simple' case of the local repository getting into an inconsistent state. I have no idea whether that's from a race condition or maybe a failed write in Julia or Git or somewhere else.
