### ISSUE TITLE
Abstract type for collection of mixed models

### ISSUE THREAD

**Issue by behinger** [JuliaStats/MixedModels.jl#325]
I saw that `MixedModelBootstrap` implements a memory-efficient collection of many mixed models, by saving only the necessary parameters. For unfold.jl it would be nice to be able to have an AbstractType to tune it to my application (which is many MixedModels, but not many Bootstraps).

What I am doing is running many mixed models, for instance one per electrode/voxel (could be thousands of voxels) and one per timepoint (could be thousands of timepoints as well). Saving only the necessary info seems important there.

**Comment by palday** [comment]
I think that profiles (#249) could also potentially fit into this framework. I think instead of `MixedModelBootstrap`, we would have something like `MixedModelFitCollection`. I'm open to alternatives on the name, but I think we should emphasize that it's a collection of fits more than the models themselves -- we're tracking the optimization settings and results, but not the data that are in the model in the `L`  and `A` matrices and the response vector.

**Comment by palday** [comment]
@dmbates While we're all thinking about types lately -- do you have any obvious thoughts on this?

**Comment by dmbates** [comment]
@palday Sounds interesting.  I think that for the time being I will stay in the background on this one and let you two consider this, if that is okay.

@behinger I admire your initiative in looking in detail at the implementation of something like the parametric bootstrap.

**Comment by palday** [comment]
It would be a non breaking change to later introduce an abstract type `MixedModelFitCollection` that `MixedModelBootstrap` extends. We see which methods it makes sense to widen to `MixedModelFitCollection` as we get the profile stuff done and see which bits `unfold` needs.
