### ISSUE TITLE
Trying to write a simulate function

### ISSUE THREAD

**Issue by gyansinha** [JuliaStats/MixedModels.jl#354]
I'm trying to write a simulate function for the following model and struggling a bit with it. The model as specified and estimated is supposed to capture a hierarchy of 5 nested levels, as below:

```
Linear mixed model fit by REML
 Formula: xsret ~ xsrm + smb + hml + ((xsrm + smb + hml) | ticker) + ((xsrm + smb + hml) | sector) + ((xsrm + smb + hml) | industry) + ((xsrm + smb + hml) | industry_group) + ((xsrm + smb + hml) | sub_industry)
 REML criterion at convergence: -625396.4847138089

Variance components:
                    Column        Variance        Std.Dev.      Corr.
 ticker         (Intercept)  0.000000005476608 0.000074004109
                xsrm         0.025925085385465 0.161012687033 -0.24
                smb          0.029417508590820 0.171515330483  0.68  0.40
                hml          0.041282267773562 0.203180382354 -0.27  0.20  0.28
 sub_industry   (Intercept)  0.000000006046889 0.000077761746
                xsrm         0.005599697044042 0.074831123498 -0.00
                smb          0.019530417927169 0.139751271648  0.29 -0.01
                hml          0.020799844539862 0.144221512056 -0.13  0.31  0.38
 industry       (Intercept)  0.000000000000000 0.000000000000
                xsrm         0.003864759444113 0.062167189450   NaN
                smb          0.006923122200769 0.083205301518   NaN  0.66
                hml          0.010220603430107 0.101097000104   NaN -0.23  0.03
 industry_group (Intercept)  0.000000049631034 0.000222780237
                xsrm         0.003575789953349 0.059797909272 -0.34
                smb          0.012668964740282 0.112556495771 -0.68  0.82
                hml          0.038853596624234 0.197113156903 -0.07  0.87  0.71
 sector         (Intercept)  0.000000000000000 0.000000000000
                xsrm         0.007924285494918 0.089018455923   NaN
                smb          0.005372457974410 0.073297052972   NaN  0.70
                hml          0.010047151129842 0.100235478399   NaN -0.64 -0.99
 Residual                    0.000243548160052 0.015606029606
 Number of obs: 114233; levels of grouping factors: 94, 57, 39, 19, 10

  Fixed-effects parameters:
────────────────────────────────────────────────────────
                 Estimate   Std.Error   z value  P(>|z|)
────────────────────────────────────────────────────────
(Intercept)  -0.000157596  7.24007e-5  -2.17671   0.0295
xsrm          1.01117      0.0400597   25.2416    <1e-99
smb           0.0711637    0.0478777    1.48636   0.1372
hml           0.263479     0.0670925    3.92711   <1e-4
────────────────────────────────────────────────────────
```

I am trying to write a simulation program that would take a new observation with a known values for xsrm, smb, and hml, and the group indicators and generate samples based on the fixed effect means and SDs and the group-level covariance matrices? TBH, I'm struggling a bit with how to frame this out. 

One of the problems I am having is being unable to extract the covariance matrices of the group-level effects. I can do this:
```
rho = VarCorr(fm1).ρ[1]

4×4 Array{Float64,2}:
  1.0       -0.236345  0.679211  -0.26572
 -0.236345   1.0       0.402258   0.201216
  0.679211   0.402258  1.0        0.280646
 -0.26572    0.201216  0.280646   1.0
```
to get the correlation matrix for the first group-level. How do I get the covariance matrix from this? When I do
```
VarCorr(fm1).σ[1]
-element Array{Float64,1}:
  0.004742020285162248
 10.31733830458864
 10.990324561577925
 13.019351333341309
```
I get variances that look quite different from what is reported using:
```
VarCorr(fm1)
Variance components:
                    Column        Variance        Std.Dev.      Corr.
 ticker         (Intercept)  0.000000005476608 0.000074004109
                xsrm         0.025925085385465 0.161012687033 -0.24
                smb          0.029417508590820 0.171515330483  0.68  0.40
                hml          0.041282267773562 0.203180382354 -0.27  0.20  0.28
 sub_industry   (Intercept)  0.000000006046889 0.000077761746
                xsrm         0.005599697044042 0.074831123498 -0.00
                smb          0.019530417927169 0.139751271648  0.29 -0.01
                hml          0.020799844539862 0.144221512056 -0.13  0.31  0.38
 industry       (Intercept)  0.000000000000000 0.000000000000
                xsrm         0.003864759444113 0.062167189450   NaN
                smb          0.006923122200769 0.083205301518   NaN  0.66
                hml          0.010220603430107 0.101097000104   NaN -0.23  0.03
 industry_group (Intercept)  0.000000049631034 0.000222780237
                xsrm         0.003575789953349 0.059797909272 -0.34
                smb          0.012668964740282 0.112556495771 -0.68  0.82
                hml          0.038853596624234 0.197113156903 -0.07  0.87  0.71
 sector         (Intercept)  0.000000000000000 0.000000000000
                xsrm         0.007924285494918 0.089018455923   NaN
                smb          0.005372457974410 0.073297052972   NaN  0.70
                hml          0.010047151129842 0.100235478399   NaN -0.64 -0.99
 Residual                    0.000243548160052 0.015606029606
```
Sorry for the long post, any help greatly appreciated, my environment details below:

```
versioninfo()

Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2470 v2 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, ivybridge)
Environment:
  JULIA_CMDSTAN_HOME = /home/gsinha/admin/src/stan/cmdstan/
  JULIA_EDITOR = code
```
```
using Pkg; Pkg.status()

Status `~/.julia/environments/v1.5/Project.toml`
  [336ed68f] CSV v0.7.7
  [324d7699] CategoricalArrays v0.8.1
  [593b3428] CmdStan v6.0.7
  [a93c6f00] DataFrames v0.21.6
  [31c24e10] Distributions v0.23.8
  [8e58cd20] Gutils v0.1.0 `../../dev/Gutils`
  [cd3eb016] HTTP v0.8.17
  [7073ff75] IJulia v1.21.2
  [b27bd851] Iex v0.1.0 `../../dev/Iex#master`
  [194296ae] LibPQ v1.5.0
  [ff71e718] MixedModels v1.1.6
  [76087f3c] NLopt v0.6.0
  [bac558e1] OrderedCollections v1.3.0
  [b98c9c47] Pipe v1.3.0
  [1a8c2f83] Query v1.0.0
  [3646fa90] ScikitLearn v0.6.2
  [1277b4bf] ShiftedArrays v1.0.0
  [191fdcea] TOML v0.4.0 `https://github.com/JuliaLang/TOML.jl.git#master`
  [112f6efa] VegaLite v2.3.0
  [a5390f91] ZipFile v0.9.2
```

**Comment by palday** [comment]
There's a few strange things in your output:

1. You have NaNs in the random effects. This is not a good sign and should not occur for correctly specified models. I suspect this is because the intercept term in those random effects is going towards zero, but that's unusual in my experience. Usually the other terms go to zero first .....

2. `  [ff71e718] MixedModels v1.1.6`  The current release is 2.3.0 and we're working hard towards a 3.0 release in the near future. I'm kinda surprised that you didn't run into other package conflicts for such an old release. I really recommend upgrading to 2.3.0 for better package compatibility and use of the current StatsModels handling of formulae. If this is due to the other issue you raised (#351), then that should be fixed in the next few days (see #352). In the meantime, you can use the proposed fix with:
```julia
julia>] add MixedModels#julia15
```

All that said, there's actually already [a `simulate!` function in MixedModels](https://github.com/JuliaStats/MixedModels.jl/blob/5894290cf8baa0ba0e1ce161a9dc3dff66c4d4fc/src/simulate.jl#L124-L143). One of the big changes in the upcoming 3.0 release is that the bootstrap has been greatly improved, but I think that the `simulate!` functionality remains largely unchanged.

Note the `!` in the name: `simulate!` overwrites the response in the model, so if you want to preserve your original fit, then you should make a `deepcopy` first. After `simulate!`, you need to call `refit!`.

This comes to the final point: only the lower Cholesky factor of the random effects is actually stored and manipulated in the model; this is the `theta` property.   The [docs](https://juliastats.org/MixedModels.jl/stable/optimization/#Linear-Mixed-Effects-Models-1) have more details on this.

For your computations by hand: remember that the random effects are scaled by the residual variance. Since you're  doing things on the standard deviation scale:

```julia 
julia> 0.015606029606  .* [0.004742020285162248, 10.31733830458864, 10.990324561577925, 13.019351333341309]
4-element Array{Float64,1}:
 7.400410896249462e-5
 0.16101268703652816
 0.17151533048753406
 0.20318038235904004
```

Which gives you back the numbers reported in the model summary,

**Comment by dmbates** [comment]
@palday Actually it is possible to have the estimated standard deviation for the intercept random effect be zero which leads to the NaN's in the correlation.  That is what is happening here.  It means that the singularity in the λ matrix includes a zero in the (1,1) position, not the lower right corner which is more common.

**Comment by gyansinha** [comment]
@palday @dmbates  thanks for your responses. I have a much better handle on things after your comments.

1. As @dmbates pointed out, that's exactly what's going on - the model I'm working with is a factor model for explaining equity returns and the intercepts are evidence of excess returns not explained by the market. In certain configurations of groups, it looks like that term is truly 0. I have addressed this by dropping the intercept for certain of the groups.

2. The reversion to the older release was a huge screw-up on my part in not noticing - I still can't figure out when and how it happened. Anyhow, as per your instructions, it's fixed now.

3. Thanks for clarifying the scaling impact of the residual variance, that cleared it up for me. 

In closing, this is what my final specification looks like
```
fm = @formula(
    xsret ~ xsrm + smb * hml + (xsrm + smb * hml|ticker) + 
    (xsrm + smb * hml|sub_industry) + (0 + xsrm + smb * hml|industry) + 
    (xsrm + smb * hml|industry_group) + (0 + xsrm + smb * hml|sector)
)
```

One thing I'm still trying to get a handle on is the way in which MixedModels in Julia deals with nested categories, seems there are clearly specified ways in which lmer or glmer handle it versus the treatment here. It'd be great to get some clarification on that as I couldn't find anything in the docs addressing this.

In closing, I am blown away by the speed of the estimation routines.

**Comment by palday** [comment]
Nested categories in MixedModels are handled exactly the same way they are in lme4.  You don't have to specify nesting explicitly if the group labels are unique / appropriate. So if sub-label A (so in your example level `A` of the grouping variable `sub_industry`) appears under both label X  and label Y (i.e. levels `X` and `Y` of the grouping variable `industry`), then it should refer to a crossed design where things belong to two different groupings simultaneously. Otherwise, you need to make the labeling explicit, either by renaming A to e.g. "X_A" and "Y_A" OR using the nesting syntax (`industry/sub_industry`). If however, A only appears under X, then the methods used in MixedModels (and lme4) will deal with the implicit nesting automatically and the explicit nesting syntax is redundant / not necessary. (I hope I made things clearer and not more confusing with that very compact explanation.)

I'm guessing that when you forced the upgrade to NLopt 0.6, the package manager looked for a MixedModels version that had a compatibility entry that worked for that. Some of the compatibility requirements were underspecified in older versions, so it kindly installed the older version for you which wasn't explicitly incompatible.

**Comment by gyansinha** [comment]
@palday thanks for your response regarding the nesting specification - seems like my data set is structured as per your second case so the nesting should be handled automatically. 

One other clarification question - let's say you have a situation where there are 3 levels, say students within classrooms within schools, but one school has only one classroom, how does the model handle a situation like this? In a sense, there is a "unbalanced" nesting structure. For now, I am just ignoring this issue, but I do see it in my data set for a very small number of the sub-industry category where the industry and sub-industry categories have the same label.

Thanks for your help - much obliged.

**Comment by palday** [comment]
Unbalanced nesting structures such as "partially crossed designs" aren't an issue for estimation either. :) More important is that you have overall a reasonable number of levels of each grouping variable total (e.g. ~5+ different groups for each blocking variable; more is of course always better).  In your particular example, the shrinkage inherent in the random effects will tend to shrink either the classroom-level or the school-level offset (more technically: BLUP / conditional mode) for that case towards zero. Of course, if every school has only classroom, then things will start to break down.

**Comment by gyansinha** [comment]
thankfully, it seems to happen only in a couple of instances at the industry/sub-industry levels. This wraps up my issues, and once again thanks for your help.

**Comment by palday** [comment]
@gyansinha Glad to help. There's a new patch release that adds Julia 1.5 support into the mainline, so you can go back to that with:

```julia
julia>] add MixedModels
```
