### ISSUE TITLE
Drop named argument to ranef now that we have raneftables

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#389]
If we drop the `named` argument to `ranef`, now that we have `raneftables`, we can remove the dependency on the `NamedArrays` package.  Shall we do that?

**Comment by palday** [comment]
I like being able to see the names for a sanity check when I'm dealing with the `ranef` directly, but I'm also part of a small set of users who do that.

I think dropping the `named` argument makes sense now -- it's a breaking API change (i.e. requires a major release) and if it turns out that there is widespread demand for it, we can bring it back in a minor release.
