### ISSUE TITLE
Document that model matrix is always at least double precision / Float64

### ISSUE THREAD

**Issue by palday** [JuliaStats/MixedModels.jl#407]
Just marking this from our internal todo list. I think this is the last MixedModels 3.0 issue without an active PR. :smile:

**Comment by dmbates** [comment]
I am taking a bit longer than anticipated to do this because I decided to see if I can construct and fit a model like
```julia
fit(MixedModel, @formula(BigFloat(yield) ~ 1 + (1|batch)), MixedModels.dataset(:dyestuff))
```
It hardly seems worth it to allow for AbstractFloat type as a struct parameter unless we can actually use it.

**Comment by dmbates** [comment]
I may end up compromising a bit and only doing this for `ReMat`, not `AbstractReMat`

**Comment by palday** [comment]
Fair, but be careful -- I think we need to watch out that `ReMat` and `FeMat` have compatible `eltype`s.

**Comment by dmbates** [comment]
This is all being done in the constructor for `LinearMixedModel`.  `FeMat` is comparatively easier to handle because it is constructed from a Matrix so you can change the element type at the time of construction.  With `ReMat` I think it will be necessary to create it then, if necessary, change the element type by constructing another `ReMat`.  At least, that's what I am doing at present.

We'll see if it works.

**Comment by dmbates** [comment]
Well, it was a nice idea and I got most of the model constructed with `BigFloat` but then I remembered that we use the NLopt optimizers which are based on compiled code which only allows for `Float64` vectors in the optimization.

I have checked my changes into a `generalTinLMM` branch but will just make a documentation change in a `documentFloat64` branch to close this.

**Comment by palday** [comment]
Is the restriction on the optimization only for the objectives parameters and value? 

I guess it doesn't really matter since the objective's parameters map 1-1 onto the `reterms`, so it's the same as having a restriction on them.

**Comment by dmbates** [comment]
It might be possible to map a `Vector{Float64}` parameter to a different floating point type in the lambda matrices for the reterms but trying to keep track of the numerical properties would be very confusing.

Another approach would be to use a native Julia optimizer which would allow for different floating point types.  My problem with that is not having found an optimizer as good as BOBYQA for gradient-free nonlinear optimization with box constraints.

One thing we could do is to make the interface to the optimizer less NLopt-specific so that other optimizers could be plugged in for testing.   I'll take a look at https://github.com/JuliaOpt/MathOptInterface.jl to see if that could work to abstract out the optimizer interface.
