### ISSUE TITLE
Parse string for @formula

### ISSUE THREAD

**Issue by Ossifragus** [JuliaStats/MixedModels.jl#426]
When I tried to use an expression parsed from a string, I got some error. Here is the code:
```julia
fix = join("x".*string.(1:3), "+")
ran = join("z".*string.(1:2), "+")
f = Meta.parse("y~1+$(fix) + ($(ran)|g)")
fm = @formula(f)
```
The following is the error message.

julia> fm = @formula(f)
ERROR: LoadError: type Symbol has no field head
Stacktrace:
 [1] getproperty(::Symbol, ::Symbol) at ./Base.jl:33
 [2] @formula(::LineNumberNode, ::Module, ::Any) at /home/ossifragus/.julia/packages/StatsModels/cpRh6/src/formula.jl:61
in expression starting at REPL[92]:1

**Comment by kleinschmidt** [comment]
This is at least partly a StatsModels.jl issue, partly a mixedmodels issue, and partly a julia/macro issue.

I think what you're trying to do is construct a formula from a list of variable names.  For more information on that, see the docs for statsmodels on constructing a formula at run-time: https://juliastats.org/StatsModels.jl/stable/formula/#Constructing-a-formula-programmatically-1.  You can do the fixed effects part easily:

```julia
julia> fix = term(1) + sum(term.("x$n" for n in 1:3))
1
x1(unknown)
x2(unknown)
x3(unknown)
```

The mixedmodels issue is that constructing a random-effects term at run-time using that technique is tricky, but it can be done.  The reason is that you have to construct the special `RandomEffectsTerm` used by mixedmodels, but that's assumed to happen after the schema has already been extracted (see this section of the statsmodels docs: https://juliastats.org/StatsModels.jl/stable/internals/#The-lifecycle-of-a-@formula-1, and this code from mixedmodels on how the random effects syntax with `|` is implemented: https://github.com/JuliaStats/MixedModels.jl/blob/master/src/randomeffectsterm.jl; note especially how the constructor for `RandomEffectsTerm` checks whether the grouping is an interaction or categorical term, which is only known after the schema is applied).  This is to my mind a legitimate quality of life issue.  At the moment you'll have to construct the concrete versions of all the terms and assemble the RandomEffectsTerm manually.  While this technically works (in that it will give you a formula you can fit with mixedmodels) it isn't going to give you any of the bumpers that mixedmodels normally provides (e.g., if you create multiple random effects terms this way, then you might end up with ... "interesting" (mis-specified) models), so it's definitely a "here be dragons" kinda thing that we should fix.  So with the caveat that I'm handing you a big foot-gun here, this is how I'd do it:

```julia
julia> ran = sum(term.("z$n" for n in 1:2))
z1(unknown)
z2(unknown)

julia> ran = apply_schema(sum(term.("z$n" for n in 1:2)), schema(dat), MixedModel)
z1(continuous)
z2(continuous)

julia> grouping = StatsModels.concrete_term(term(:g), dat, Dict(:g => Grouping()))
g(Grouping:5→5)

julia> reterm = MixedModels.RandomEffectsTerm(ran, grouping)
(z1 + z2 | g)

julia> formula = term(:y) ~ term(1) + fix + reterm
FormulaTerm
Response:
  y(unknown)
Predictors:
  1
  x1(unknown)
  x2(unknown)
  x3(unknown)
  (z1 + z2 | g)
```

This gets us most of the way there but it still doesn't work unfortunately.  The issue is that MixedModels tries to extract a schema and doesn't recognize that `RandomEffectsTerms` don't need them...we can duck patch that by defining `StatsModels.needs_schema(::RandomEffectsTerm) = false` but that's better fixed here or in statsmodels IMO.

In the interest of fixing this the right way, here are the missing pieces in MixedModels at the moment

- [ ] make `apply_schema(::FunctionTerm{typeof(|)}, ...)` create an "non-concrete" `RandomEffectsTerm`
- [ ] add additional `apply_schema(::RandomEffectsTerm, ...)` which makes it concrete, does the validity checks done in teh inner constructor right now
- [ ] add run-time methods for `Base.|(::AbstractTerm, ::AbstractTerm)` to create a `RandomEffectsTerm`, or if we don't want to do type piracy, use a different syntax (like `re` or `reterm` or something...)

Finally, the most superficial reason why your attempt doesn't work is a Julia/macro issue: `@formula(f)` only sees one thing as its argument, the Symbol `:f`.  Macros in julia can only do transformations of the surface syntax (symbols, exprs, strings, and literal numbers).  Reading the docs on macros in julia will be helpful, and people on slack/discourse/zulip can answer other questions in that direction.  If you're going to go this way (which is not recommended), then you need to use `eval` and `$f`.

**Comment by Ossifragus** [comment]
@kleinschmidt Thank you so much for providing the solution with detailed explanation. I will learn it more carefully. Here is an error when I run
```julia
grouping = StatsModels.concrete_term(term(:g), dat, Dict(:g => Grouping()))
reterm = MixedModels.RandomEffectsTerm(ran, grouping)
```
I still get the following error. The variable `g` is categorical in the data frame `dat`. Did I miss anything here? Many thanks again.
```julia
ERROR: ArgumentError: blocking variables (those behind |) must be Categorical (g is not)
Stacktrace:
 [1] RandomEffectsTerm(::Tuple{ContinuousTerm{Float64},ContinuousTerm{Float64}}, ::Term) at /home/ossifragus/.julia/packages/MixedModels/Bt3fL/src/randomeffectsterm.jl:7
 [2] top-level scope at REPL[29]:1
```

**Comment by palday** [comment]
@Ossifragus Can you provide a MWE of this? 

The check for `Categorical` in MixedModels is mostly to prevent the passing of a numeric variable as a grouping term, which is a surprisingly common misunderstanding. (It also forces the encoding of integer-valued labels as categorical to make it very clear that this is something where only categorical variables make sense.)

**Comment by Ossifragus** [comment]
@palday Thank you for your explanation. Please see the following example. I am using DataFrames v0.21.8, StatsModels v0.6.15, and MixedModels v2.4.0.

```julia
using Random, StatsModels, DataFrames, MixedModels
Random.seed!(1);
n = 10
x1=rand(n); x2=randn(n); dx = 2;
z1=rand(n); z2=rand(n);  dz = 2;
g=categorical(string.(rand(1:3, n)));
y = randn(n);
dat = DataFrame(x1=x1, x2=x2, z1=z1, z2=z2, g=g, y=y)

fix = term(1) + sum(term.("x$n" for n in 1:dx))
ran = apply_schema(sum(term.("z$n" for n in 1:dz)), schema(dat), MixedModel)
grouping = StatsModels.concrete_term(term(:g), dat, Dict(:g => Grouping()))
reterm = MixedModels.RandomEffectsTerm(ran, grouping)
```

**Comment by palday** [comment]
So I don't yet know how to fix the problem, but the underlying problem is this:

```julia
julia> grouping = StatsModels.concrete_term(term(:g), dat, Dict(:g => Grouping()))
g(unknown)
```

Note that in @kleinschmidt's example, the contrasts were already specified at this point.

Somewhat related: MixedModels 3.0 is out now and unless you're depending on the way bootstrap samples were stored in 2.x, you can probably upgrade without any problems. There a few edge cases (e.g. handling of rank-deficiency, how `(1|g) + (x|g)` is interpreted), but these shouldn't impact most users -- And the impacted users have probably already had difficulties under the old behavior.

**Comment by palday** [comment]
Ah, the fix is simple. You need to pass the term's data (i.e. a vector) and not the entire table for `concrete _term`:

```julia
julia> grouping = StatsModels.concrete_term(term(:g), dat.g, Dict(:g => Grouping()))
g(Grouping:2→2)

julia> reterm = MixedModels.RandomEffectsTerm(ran, grouping)
(z1 + z2 | g)
```

**Comment by Ossifragus** [comment]
@palday Fantastic! Thank you so much!

**Comment by Ossifragus** [comment]
@palday I have an unrelated question. How to update to MixedModels 3.0? `update MixedModels` always gave me the version 2.4.0.  `add https://github.com/JuliaStats/MixedModels.jl` give me the following error. Thanks.
```
    Cloning git-repo `https://github.com/JuliaStats/MixedModels.jl`
   Updating git-repo `https://github.com/JuliaStats/MixedModels.jl`
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Arrow [69666777]:
 Arrow [69666777] log:
 ├─possible versions are: [0.1.2, 0.2.0-0.2.4, 0.3.0, 0.4.0] or uninstalled
 ├─restricted to versions 0.3-0.4 by MixedModels [ff71e718], leaving only versions [0.3.0, 0.4.0]
 │ └─MixedModels [ff71e718] log:
 │   ├─possible versions are: 3.1.0 or uninstalled
 │   └─MixedModels [ff71e718] is fixed to version 3.1.0
 └─restricted by compatibility requirements with Feather [becb17da] to versions: [0.1.2, 0.2.0-0.2.4] — no versions left
   └─Feather [becb17da] log:
     ├─possible versions are: [0.4.0, 0.5.0-0.5.6] or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions [0.4.0, 0.5.0-0.5.6]
```

**Comment by palday** [comment]
There is a conflict between Arrow (which MixedModels now stores its test data in) and Feather (which MixedModels used to store its test data in). If you're not using Feather for anything else, then you can `rm MixedModels Feather` and then `add MixedModels`.

**Comment by Ossifragus** [comment]
@palday Got it. Many thanks.
