### ISSUE TITLE
ftest for GLMM

### ISSUE THREAD

**Issue by DarioSarra** [JuliaStats/MixedModels.jl#503]
Is there a plan to extend this function from GLM to GLMM?  Being this based on DOF and Deviance I imagine mixedmodels should compatible with this analysis as well, right?

**Comment by palday** [comment]
No, for a few reasons:
- for LMM, the denominator degrees of freedom aren't well defined. If you take them to be effectively infinite (as we do in the `show` methods), then you get z-values instead of t-values and chi-square instead of F-values. For somewhat obvious reasons, we don't want to do a Chi-square test instead of an F-test.
- If you want a Chi-square test, then `StatsModels.lrtest` or `MixedModels.likelihoodratiotest` will provide that for you. (There are [deep reasons](https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faqhow-are-the-likelihood-ratio-wald-and-lagrange-multiplier-score-tests-different-andor-similar/) why a likelihood-ratio test behaves like an asymptotic F-test as the denominator degrees of freedom go to infinity!)
- The output from GLM shows R² values, which are [not particularly well defined for LMM](https://marc.info/?l=r-sig-mixed-models&m=126719474831488&w=2), somewhat inadvisable for GLM, and, in my opinion, flat-out misleading for GLMM (which combines all the problems of LMM and GLM).

I *might* consider a PR for inclusion in [MixedModelsExtras.jl](https://github.com/palday/MixedModelsExtras.jl), but it would definitely require a suitable docstring with lots of warnings (see e.g. the [warnings for the naive R² measure](https://github.com/palday/MixedModelsExtras.jl/blob/1754e255ade116603e06109b10b0a11a776edf16/src/r2.jl#L1-L43) implemented there.). It's not high priority for me at all, so it's unlikely to happen without an external PR.
