### ISSUE TITLE
Predict: Response column must be initialized to a non-missing numeric value

### ISSUE THREAD

**Issue by jariji** [JuliaStats/MixedModels.jl#626]
```jl
julia> MixedModels.predict(fitval, d)
ERROR: ArgumentError: Response column must be initialized to a non-missing numeric value.
```

Why is the response column required? I am not using it in my prediction.

**Comment by palday** [comment]
Because internally a new model is constructed to simplify the bookkeeping and that model requires a response, even it is nothing but a column of zeros.

This is explained in the [docstring for predict](https://juliastats.org/MixedModels.jl/stable/api/#StatsAPI.predict-Tuple{LinearMixedModel,%20NamedTuple{names,%20T}%20where%20{N,%20D,%20names,%20T%3C:Tuple{Vararg{AbstractArray{S,%20D}%20where%20S,%20N}}}}).

There are plans to loosen this requirement: https://github.com/JuliaStats/MixedModels.jl/issues/601.
