### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by donaldRwilliams** [JuliaStats/MixedModels.jl#629]
Hi,
I ran into this error. My data is very big.. millions of students..

How might I use "Grouping" ?

![image](https://user-images.githubusercontent.com/19657194/181391551-676da474-1ebd-4dc8-a482-0a19acab778d.png)

**Comment by palday** [comment]
If you copy and paste the text (even including the Julia prompt) instead of taking a screenshot, it's easier to show how to modify your command to work. You don't need to specify the formula in R either:

```julia
fit(MixedModel, @formula(rit ~ 1 + iwks + (1 + iwks|grade)),
    rcopy(R"dat_julia"); 
    contrasts=Dict(:grade => Grouping()))
```

**Comment by donaldRwilliams** [comment]
Thank you !! I will do that in the future, for sure.

**Comment by palday** [comment]
I didn't see anything in your example that was easier in R, but if you still need access to R, check out [JellyMe4](https://github.com/palday/JellyMe4.jl), which improves RCall support for MixedModels.

**Comment by donaldRwilliams** [comment]
Hi.. I am running into this error again, even with ` contrasts=Dict(:grade => Grouping())`

The same model can be fitted in R using `glmmTMB`

Do you have any other tips for addressing memory issues ?

**Comment by palday** [comment]
Without knowing more about the data, it's hard to say. 

If you're using RCall to load the dataframe, then it's possible that you have two copies of the data in memory: one in R and one in Julia. With [`RData.jl`](https://github.com/JuliaData/RData.jl), [`CSV.jl`](https://csv.juliadata.org/stable/index.html) or [`Arrow.jl`](https://arrow.juliadata.org/stable/), you could load the data directly in Julia. Arrow will probably give you best performance, if you're able to save your data in Arrow format, e.g. with the [`arrow` package](https://arrow.apache.org/docs/r/) (where the function you're looking for is confusing called `write_feather` because the predecessor to Arrow was Feather).

I don't know how well `Grouping()` plays with interactions `&`. If `id` is already unique within `ncesid`, the the combination `id&ncesid` isn't any different in terms of model specification than `id` and so you could try to fit the model with `id`. Otherwise, you could try computing the combination ahead of time, e.g. `transform!(df, [:id, :ncesid] => ByRow( (x,y) -> string(x, "&", y)) => :id)` and then you wouldn't need the `&` in the model specification.

If you're able to share the data -- even privately -- then I may be able to provide more feedback. For that, you can reach out via the Julia Slack, Julia Zulip or on the Julia Discourse.

**Comment by donaldRwilliams** [comment]
Thanks for this.

Unfortunately, I cannot likely share the data. 

I do have quite a bit of students (`id`). For example, in that last shared model, there are 16,000 students. The strange thing is that `a0` is the intercept, so all 1's, and if this is removed from the model, i.e., 

```
(fm1 = fit(LinearMixedModel, 
@formula(rit ~  a1 + a2 + b0 + b1 + c0 + ( a1 + b0 + b1  | ncesid) + ( a1 + b0 + b1  | id) ), 
df,  REML = false, σ=1, contrasts=Dict(:id => Grouping(), :ncesid => Grouping())))
```

I do not run into the memory issues. 

This is also data from just two states, so I think when scaling it up, we will likely have to use a different computer anyhow.

**Comment by palday** [comment]
@kleinschmidt might know why "full dummy" (the model without the intercept) leads to more memory use than the model with the intercept. 

Have you seen our tinkerings on a truly massive (25 million observation) dataset? 
https://dmbates.github.io/ml-25mjl/ gives an idea of the minimum memory requirements based just on the amount of information in the dataset. For that dataset, we are currently fitting a model of comparable complexity to your model on a machine with 32GB of RAM. 

We have also fit models to ~2.5 million observations on more modest hardware: https://github.com/dmbates/EnglishLexicon.jl/.

In theory, we can fit models with the fixed effects stored as a sparse matrix, but we don't have a great interface for that (and you would have construct your own model matrix). Generally speaking, the sparsity pattern in the fixed effects isn't worth the overhead of sparse matrix methods and it's just faster and easier to treat them as dense (hence the lack of a convenient interface).

**Comment by donaldRwilliams** [comment]
Quick check in.

I am now fitting the full data set that includes 7.5 million rows.. roughly 4 million students (level 2), and 1000s of schools (level 3). By avoiding the "full dummy" & using `transform!(df, [:id, :ncesid] => ByRow( (x,y) -> string(x, "&", y)) => :id)`, it is hardly putting a dent into the memory (32 GB RAM). It is humming (slowly, 2.5 seconds per iteration) at about 60 % memory usage, as indicated in the task manager.. 

Pretty cool !!

**Comment by kleinschmidt** [comment]
> So it seems perhaps the 0 + in the random effects part of the formula is maybe causing the issue ?

Yeah that was my hunch too.  FWIW I don't think there's any reason to use `0 + a0` instead of `1`, even if you want `a0` to be some other constant value, since it'll still be linearly equivalent to the model with all 1s unless I'm missing something.  And using `0` messes up the built-in logic about adjusting contrast coding based on redundancy in the model matrix (e.g., `0 + a0 + a1` with `a1` categorical will expand `a1` into full-dummy coding, _even if_ `a0` has all 1s).

My other hunch which you've also mentieond above is the interaction in the grouping vars for the ranefs; I'm not sure how well we handle that right now.
