### ISSUE TITLE
possible to fix the residual variance to a particular value

### ISSUE THREAD

**Issue by donaldRwilliams** [JuliaStats/MixedModels.jl#630]
I am coming over from R, and in particular it is possible to fix sigma when using `nlme`. so, e.g., it can be constrained to 1. 

I am wondering if this is possible in MixedModels ?

**Comment by palday** [comment]
Yes, you just specify σ in the call to `fit`.

```julia
fit(MixedModel, @formula(y ~ 0 + (1|z)), dat;
             contrasts=Dict(:z => Grouping()),
             σ=1)
```

In Julia, you can type Greek letters by typing backslash followed by name and pressing tab, e.g. `\sigma` + TAB will give you `σ`.

**Comment by kliegl** [comment]
Is this a special case or do you also allow, for example, equality constraints for parameters now?

**Comment by donaldRwilliams** [comment]
> Yes, you just specify σ in the call to `fit`.
> 
> ```julia
> fit(MixedModel, @formula(y ~ 0 + (1|z)), dat;
>              contrasts=Dict(:z => Grouping()),
>              σ=1)
> ```
> 
> In Julia, you can type Greek letters by typing backslash followed by name and pressing tab, e.g. `\sigma` + TAB will give you `σ`.

That is really cool !!!

**Comment by palday** [comment]
@kliegl This is currently the only user specified constraint. 

For the linear mixed model, fixed effects are profiled out, so allowing constraints on them would require a completely different and much slower code path (because it would require optimizing over them, much like `fast=slow` in the general linear mixed model). From a user perspective, the resulting entity would be different enough that we would probably want to introduce a new `ConstrainedMixedModel` type. It would probably be enough code to deserve its own package. For the generalized linear mixed model, you can already specify constraints on the lower bound via optsum when `fast=false`. I suppose we could add an upper bound, which just defaults to infinity/unbounded (which is implicitly what we do now).

Simple constraints on the random effects can be made by specifying an alternative lower bound in `optsum`; more complex constraints like compound symmetry, etc. would require implementing an something like we have for `ZeroCorr` (which IIRC is analogous to nlme's `pdDiag`), but more complicated in practice. The analog to nlme's `pdIdent` would be straightforward, but I haven't seen a compelling enough use case to prioritize the work required. You can accomplish something like `pdBlocked` just be separating out the blocks into separate `(...|grp)` terms.
