### ISSUE TITLE
Add TypedTables as a dependency to make it easier to return tables from simulations?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#631]
At present the allpars property of a parametric bootstrap sample is usually converted immediately to a DataFrame for manipulation.  We probably don't want to have MixedModels.jl depend on DataFrames.jl but should we consider a dependency on TypedTables.jl?  It is a much lighter weight package than DataFrames.jl and could suffice for most of our uses.

**Comment by palday** [comment]
I'm not opposed to this, but it may be "lightly breaking" if any consumers are expected a concrete type instead of just a column table. That shouldn't hold us back from doing this in a minor release though as long as we're very clear in the release notes. We might also want to update the docstrings that we make guarantees about not breaking the table schema, but not necessarily about the concrete type.

Also, if this is mostly about displaying the bootstrap results -- should we add a `show` method to `MixedModelsBootstrap` that does a pretty printed allpars by default?
