### ISSUE TITLE
Level 2 or 3 weights

### ISSUE THREAD

**Issue by donaldRwilliams** [JuliaStats/MixedModels.jl#635]
I have a question about weights.

I am wondering in particular if it is possible to achieve something like this in `MixedModels`

Notice that is allows for defining level 2 weights.. and they also describe level 3 weights.. perhaps this is something I have to do, or maybe there is a way to do this already ?

![image](https://user-images.githubusercontent.com/19657194/184251058-f4d05f62-926d-4199-a069-e583b0172926.png)

My initial thought (just an idea), would be to assign all level 1 obs from same level 2 the same weight. e.g., so all kids from school A would have the same weight..

**Comment by palday** [comment]
There are a couple of terminological nitpicks here that are important for me understanding your problem. :smile: 

First, what type of weights do you want? See e.g. https://blogs.sas.com/content/iml/2017/10/02/weight-variables-in-statistics-sas.html The weights here and in GLM.jl are frequency weights. As noted in the [GLM.jl documentation](https://juliastats.org/GLM.jl/stable/api/#GLM.lm):
> The keyword argument wts can be a Vector specifying frequency weights for observations. Such weights are equivalent to repeating each observation a number of times equal to its weight. Do note that this interpretation gives equal point estimates but different standard errors from analytical (a.k.a. inverse variance) weights and from probability (a.k.a. sampling) weights which are the default in some other software. 

(The math in your screen shot here gives is clear on the meaning of weights, but I want to make sure that's the meaning you're going for -- it's not meant as a sleight, just trying to establish common ground. :smile: Also, I'm planning on some big additions to the documentation in the next weeks, so it's great to see what types of questions people have.)

Second, we don't need to segregate levels into a strict hierarchy; I personally actually find that terminology confusing! It is useful to distinguish between "observation-level" and "cluster-" or "group-level", but the actual hierarchy doesn't matter that much for the methods we use. There are two main ways to formulate the (frequentist) linear mixed model: generalized least squares (GLS) and penalized least squares (PLS). These formulations are duals of each other. In MixedModels.jl and its predecessor lme4, PLS is used. One of the great advantages of PLS is that the methods don't need to depend on a particular nesting/crossing/hierarchical structure to be quite efficient. (Methods based on GLS do usually require strong assumptions about the multilevel structure in order to have good performance, which is why it is often emphasized in other software.) From that perspective, we don't need to distinguish between Level n and n+1 once we're beyond observation level.

So back to your original question ... yes, based on the math they use for cluster weights, it looks like it's just equivalent to repeating the cluster-level weight for each associated observation. My intuition is that that makes sense, but there might be a corner case with standard errors on the variance components. Of course, we intentionally don't compute nor report standard errors on the VCs (because the associated sampling distribution is highly skewed and SE doesn't make sense), and the bootstrapped CIs should be fine.

**Comment by palday** [comment]
closing as resolved; further docs improvements are in the works
