### ISSUE TITLE
`ERROR: MethodError: no method matching r2(::LinearMixedModel{Float64})`

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaStats/MixedModels.jl#697]
```
using Tables
using MixedModels
using CSVFiles

const GLMM = GeneralizedLinearMixedModel

data = load("ICARdata.csv")
regression = @formula(SEI ~ Age + Total + Sex + (1 | Education))
model = fit(LinearMixedModel, regression, data)
r2(model)
```
Gives:
```
ERROR: MethodError: no method matching r2(::LinearMixedModel{Float64})

Closest candidates are:
  r2(::StatisticalModel, ::Symbol)
   @ StatsAPI ~/.julia/packages/StatsAPI/HGVqH/src/statisticalmodel.jl:250
  r2(::StatsModels.TableRegressionModel)
   @ StatsModels ~/.julia/packages/StatsModels/Wzvuu/src/statsmodel.jl:141
  r2(::StatsModels.TableRegressionModel, ::Symbol)
   @ StatsModels ~/.julia/packages/StatsModels/Wzvuu/src/statsmodel.jl:143
  ...

Stacktrace:
 [1] top-level scope
   @ ~/research/twitterArguments/arrogance.jl:10
```

**Comment by palday** [comment]
Indeed, there is no `r2` method defined for `LinearMixedModel`. This is an intentional decision, cf. the [GLMM FAQ](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#how-do-i-compute-a-coefficient-of-determination-r2-or-an-analogue-for-glmms).

That said, [`MixedModelsExtras`](https://palday.github.io/MixedModelsExtras.jl/stable/api) defines a few things that we don't want to officially support in MixedModels.jl, including a naive method for computing the coefficient of determination.


Unrelated to all of that, `(1|Education)` seems like a very unusual grouping variable. Grouping variables -- the bits behind the `|` aren't just nuisance variables, but rather things that define blocks of observations. Continuous variables, categorical variables with very few levels, or categorical variables with observations per level are generally not well-suited as grouping variables.
